"""
Django settings for physixed project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from __future__ import annotations

import os
import pathlib
from pathlib import Path

from dotenv import dotenv_values, load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environmental variables
load_dotenv(pathlib.Path(BASE_DIR) / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-y$lr3$o6)q^k-4mlnm!va5#inp9i6*5og7rlt98ngrc76gh^m#"  # noqa: S105

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(dotenv_values(dotenv_path=".env").get("DJANGO_DEBUG", True))

allowed_hosts_fallback = "localhost 127.0.0.1 [::1]"
ALLOWED_HOSTS = dotenv_values(dotenv_path=".env").get("ALLOWED_HOSTS", allowed_hosts_fallback).split(" ")


# Admins

ADMINS = ("Leroy Teegelbeckers", "multiduckk@gmail.com")
MANAGERS = ADMINS

# Resend

RESEND_API_KEY = os.getenv("RESEND_API_KEY")

DEVELOPER_NAME = os.getenv("DEVELOPER_NAME")
DEVELOPER_EMAIL = os.getenv("DEVELOPER_EMAIL")


# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS: list[str] = [
    # Third party apps
    #######################
    "rest_framework",
    "corsheaders",
]

LOCAL_APPS: list[str] = []

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "physixed.urls"

# Corsheaders
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "physixed.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / STATIC_URL.strip("/")
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# LOGGING
try:
    from .px_production_apps import baseline_apps, production_apps
except ImportError as e:
    msg = "CRITICAL: Can't import `px_production_apps.py`"
    raise AssertionError(msg) from e

try:
    if bool(DEBUG):
        from .px_development_apps import development_apps
except ImportError:
    msg = """
    -------------------------- `px_development_apps.py` file was not found.
    * You really should create that file by copying the template.
    * Using the production app list for now, but this is probably not what you want. *
    --------------------------
    """
    print(msg)  # noqa: T201
    development_apps = production_apps.copy()

LOG_DIR = BASE_DIR / "logs"
if not LOG_DIR.exists():
    LOG_DIR.mkdir()

FORMATTERS = {
    "verbose": {
        "()": "colorlog.ColoredFormatter",
        "format": "%(log_color)s [%(levelname)s] %(asctime)s %(name)s %(threadName)s %(thread)d %(module)s %(filename)s:%(lineno)d %(funcName)s %(process)d :: %(message)s",  # noqa: E501
    },
    "simple": {
        "()": "colorlog.ColoredFormatter",
        "format": "%(log_color)s [%(levelname)s] %(asctime)s %(name)s %(module)s %(filename)s:%(lineno)d %(funcName)s :: %(message)s",  # noqa: E501
    },
}


HANDLERS = {
    "console_handler": {"class": "logging.StreamHandler", "formatter": "simple", "level": "DEBUG"},
    "info_handler": {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": f"{LOG_DIR}/physixed_info.log",
        "mode": "a",
        "encoding": "utf-8",
        "formatter": "simple",
        "level": "INFO",
        "backupCount": 5,
        "maxBytes": 1024 * 1024 * 5,  # 5 MB
    },
    "error_handler": {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": f"{LOG_DIR}/physixed_error.log",
        "mode": "a",
        "formatter": "verbose",
        "level": "WARNING",
        "backupCount": 5,
        "maxBytes": 1024 * 1024 * 5,  # 5 MB
    },
}

LOGGERS = {
    "django": {
        "handlers": ["console_handler", "info_handler"],
        "level": "INFO",
    },
    "django.request": {
        "handlers": ["error_handler"],
        "level": "INFO",
        "propagate": True,
    },
    "django.template": {
        "handlers": ["error_handler"],
        "level": "DEBUG",
        "propagate": True,
    },
    "django.server": {
        "handlers": ["error_handler"],
        "level": "INFO",
        "propagate": True,
    },
}

for apps in [baseline_apps, production_apps, development_apps]:
    for app in apps:
        LOGGERS[app] = {
            "handlers": ["console_handler", "info_handler", "error_handler"],
            "level": "DEBUG",
            "propagate": True,
        }

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": FORMATTERS,
    "handlers": HANDLERS,
    "loggers": LOGGERS,
}
