name: Test Apps

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached $HOME/.local
        uses: actions/cache@v2.1.6
        with:
          path: ~/.local
          key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/pr-deployer.yml') }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Tests
        shell: bash -l {0}
        run: |
          cd backend
          poetry run python -m pytest .
